### ISSUE TITLE
Using resource options produces "Request was missing field timeSeries" error in the logs

### ISSUE THREAD

**Issue by geoah** [GoogleCloudPlatform/opentelemetry-operations-go#166]
Hey there,

It seems that adding resource options in the metrics exporter results in some not very informative error logs every time it tries to flush.

```
rpc error: code = InvalidArgument desc = Request was missing field timeSeries.
```

This can be easily replicated by the following service assuming it has access to GCP.
```go
	mopts := []mexporter.Option{
		mexporter.WithInterval(10 * time.Second),
	}
	ropts := basic.WithResource(
		resource.NewWithAttributes(
			attribute.String("instance_id", "abc123"),
			attribute.String("application", "example-app"),
		),
	)
	_, err := mexporter.InstallNewPipeline(mopts, ropts)
	if err != nil {
		panic(err)
	}

	<-make(chan struct{})
```

It will start logging the error mentioned above every 10 seconds.
First log takes a bit longer for some reason (up to 30 seconds).

Note: using `ropts := []basic.Option{}` does not result in the same logs.

---

I'd be really grateful if someone could help out about whether this is expected behaviour, a big, or misconfiguration on our end.

Thank you very much in advance :)

**Comment by punya** [comment]
@geoah thanks for the bug report. Let me try this out and get back to you shortly.

**Comment by geoah** [comment]
@punya if you have any ideas on what this might be related to and can point me to the right direction I could take a look as well. I just really can't pinpoint to why or where this is happening.

**Comment by ryanlaycock** [comment]
Hey, interestingly I seem to be getting the same error:

`2021/05/13 18:38:57 rpc error: code = InvalidArgument desc = Request was missing field timeSeries.`

even when using the **basic options**:

```
        opts := []mexporter.Option{
		mexporter.WithProjectID(projectID),
		mexporter.WithInterval(10 * time.Second),
	}
	ropts:= []basic.Option{}

	// Create exporter (collector embedded with the exporter).
	pusher, err := mexporter.InstallNewPipeline(opts, ropts...)
	if err != nil {
		return MetricExporter{}, err
	}
```

It happens every 10 seconds in this configuration so presume it is every time it tries to export.

**Comment by punya** [comment]
I dropped the ball on this for a few days, but I'm picking it up again shortly. Thanks for your patience!

**Comment by soellman** [comment]
I was also seeing this before:
1. I set the monitored resource type (see #170)
2. I fixed my service account's IAM permissions

Once I did both of those things, I saw this only once or twice when a new timeseries was being created and then the message went away.

**Comment by ryanlaycock** [comment]
> I was also seeing this before:
> 
> 1. I set the monitored resource type (see #170)
> 2. I fixed my service account's IAM permissions
> 
> Once I did both of those things, I saw this only once or twice when a new timeseries was being created and then the message went away.

Hi @soellman, Are you able to share more of your setup code? I have set the attributes in the same way you have (as far as I can tell) but am still facing this issue.

Also what specifically do you mean by "I fixed my service account's IAM permissions" please?

**Comment by ryanlaycock** [comment]
Hey @punya, I think I've found the issue. We seem to only get this error on collection when there is no new data to add. 

Doing `Int64UpDownCounter.Add()` once or more per the interval in which the metric exporter sends to Cloud Monitoring doesn't generate the error message, but if we don't `.Add()` to a counter in the interval then it does error.

Presumably the collector doesn't have any timeSeries to collect, hence the error `Request was missing field timeSeries.`.

**Comment by ryanlaycock** [comment]
I've ha da dig in the code and it looks like adding:
```
if len(tss) == 0 {
	return nil
}
```
to this line [here](https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/blob/5a6256f818e7d8d7244ecf3a014de4e8419b2b44/exporter/metric/metric.go#L269) fixes this. Interested to hear what you think, I can open a PR if it would help?

**Comment by punya** [comment]
@ryanlaycock that's a great find and your proposed solution also makes sense - thank you! Please do submit a PR.
